# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 04:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_text', models.TextField(max_length=10000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/cafe/blog')),
            ],
        ),
        migrations.CreateModel(
            name='CafeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth_date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cafeprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(max_length=1000)),
                ('short_description', models.TextField(max_length=150)),
                ('calories', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('sat_fat', models.IntegerField(default=0)),
                ('trans_fat', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('dietary_fiber', models.IntegerField(default=0)),
                ('sugar', models.IntegerField(default=0)),
                ('sodium', models.IntegerField(default=0)),
                ('cholesterol', models.IntegerField(default=0)),
                ('potassium', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='media/images/cafe/menu')),
                ('available', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cafe.Menu')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cafe.MealType')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_placed', models.DateTimeField(verbose_name='time placed')),
                ('is_ready', models.BooleanField(default=False)),
                ('order_for', models.CharField(max_length=50)),
                ('pickup_time', models.DateTimeField(verbose_name='pickup time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.CafeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Specials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special', models.CharField(max_length=50)),
                ('soup', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'specials',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('ticket_text', models.TextField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.CafeProfile')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='specials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Specials'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cafe.Category'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='images',
            field=models.ManyToManyField(blank=True, to='cafe.BlogPostImage'),
        ),
    ]
