# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_ticket_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sent',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time sent'),
            preserve_default=False,
        ),
    ]
