# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_ticket_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='sent',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time received'),
            preserve_default=False,
        ),
    ]
