# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_auto_20170505_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='open',
        ),
        migrations.AddField(
            model_name='ticket',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
