# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_auto_20170505_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='extra_options',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='multiple_sizes',
            field=models.BooleanField(default=False),
        ),
    ]
