# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_auto_20170505_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pickup time'),
        ),
    ]
