# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
