# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='short_description',
        ),
    ]
