# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0015_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='used_for',
            field=models.CharField(default='Blog', max_length=50),
            preserve_default=False,
        ),
    ]
