# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0017_remove_menu_specials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_placed',
            field=models.TimeField(verbose_name='time placed'),
        ),
    ]
