# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0018_auto_20170516_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
